version: 1

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: 
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/"
    schedule: 
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "javascript"

reviewers:
  - "Dynamic-Mike (tu memo)"
